# https://www.reddit.com/r/HelixEditor/comments/11f6scu/comment/jch0d3h/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
inherits = "catppuccin_macchiato"
"ui.background" = {}